type User {
  id: ID!
  firstname: String
  lastname: String
  cash: Int
  email: String
  username: String
  phoneNumber: String
  notifyOnMessageBoard: Boolean
  isAdmin: Boolean
}

input UserInput {
  firstname: String!
  lastname: String!
  cash: Int
  email: String!
  username: String!
  phoneNumber: String
  notifyOnMessageBoard: Boolean
}

type Query {
  user(email: String!): User!
  users: [User]
  usersByEntryId(entryId: ID!): [User]
}

type Mutation {
  updateUserCash(userId: ID!, cash: Int!): Boolean!
  createUser(input: UserInput!): User!
  updateUser(input: UserInput!): User!
  setUserAdmin(email: String!, isAdmin: Boolean!): User!
}
